### ISSUE TITLE
Houdini Plugin - Hangs on New Stylization

### ISSUE THREAD

**Issue by hful** [Ozeuth/Python-Houdini-Plugin-for-Tensorflow-Smoke-Stylization#1]
Hello,

I need help when I clicked on "New Stylization" its just hangs.
This issue happened when program runs into file get_vect_field.py, line 250, in "hou.session.output()".
BTW Python version is working.

====Houdini Console Log=====
`Styler Initialized
2020-06-09 22:00:12.394535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1060 5GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
totalMemory: 5.00GiB freeMemory: 4.12GiB
2020-06-09 22:00:12.395076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-06-09 22:00:13.042043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-09 22:00:13.042347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-06-09 22:00:13.042529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-06-09 22:00:13.042811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3857 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 5GB, pci bus id: 0000:01:00.0, compute capability: 6.1)`

**Comment by Ozeuth** [comment]
Dear hful,
I have had reports of this issue before, but have not had enough user information to debug this (seems to be setup dependent). The subprocess executing the Python styler has been called from Houdini. However, it seems it is getting stuck during styler initialization. Let us try and debug this:

1. A possible mistake is calling the wrong library versions. The Houdini version looks in these places for your libraries:
  - PYTHON_PATH
  - PYTHON_PATH/DLLS
  - PYTHON_PATH/Lib
  - PYTHON_PATH/Lib/site-packages
Meanwhile, your Python-only version could be finding your libraries elsewhere (eg. C:\Users\USER\AppData\Roaming\Python\Python36\site-packages, as it does for me) This creates compatibility issues. Could you check you don't have differing library versions?

2. Here are the CUDA, CuDNN and library setup I use. 
CUDA: 10.1
CuDNN: 7.6.5
tensorflow: 1.11.0
tqdm: 4.32.2
matplotlib: 3.1.1
PIL: 6.1.0
imageio: 2.5.0
scipy: 1.2.0
skimage: 0.15.0

To check, add this to styler.py and run the Houdini version
```
import tensorflow as tf
import tqdm
import matplotlib
import PIL
import imageio
import scipy
import skimage
# Run below after line "if __name__ == '__main__':"
print(tf.__version__)
print(tqdm.__version__)
print(matplotlib.__version__)
print(PIL.__version__)
print(imageio.__version__)
print(scipy.__version__)
print(skimage.__version__)
```

3. If all this fails, I should be glad to take a closer look at your setup. email me at: ozeuthgatum@gmail.com
====Houdini Console Log=====
```
Styler Initialized
2020-06-10 01:08:34.874388: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-06-10 01:08:36.084598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2020-06-10 01:08:36.104234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2020-06-10 01:13:17.630798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-10 01:13:17.631053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2020-06-10 01:13:17.631206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2020-06-10 01:13:17.664435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4726 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
# vps: 9

[*] MODEL dir: log/smoke_gun\0610_011319_fire
[*] PARAM path: log/smoke_gun\0610_011319_fire\params.json

load density fields
Added frame: 44
All Data sent!
D:\Code\Python36\Lib\site-packages\tensorflow\python\ops\gradients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
...
```

**Comment by hful** [comment]
here is my setups:

CUDA: 10.0.130
CuDNN: 7.3.1.20
tensorflow: 1.12.0
tqdm: 4.46.0
matplotlib: 3.2.1
PIL: 7.1.2
imageio: 2.8.0
scipy: 1.4.1
skimage: 0.17.2

`C:\Windows\system32>python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> for p in sys.path:
...    print(p)
...

C:\Users\Users\AppData\Local\Programs\Python\Python36\python36.zip
C:\Users\Users\AppData\Local\Programs\Python\Python36\DLLs
C:\Users\Users\AppData\Local\Programs\Python\Python36\lib
C:\Users\Users\AppData\Local\Programs\Python\Python36
C:\Users\Users\AppData\Local\Programs\Python\Python36\lib\site-packages
>>> import os
>>> os.environ['PYTHON_PATH'].split(os.pathsep)
['C:\\Users\\Users\\AppData\\Local\\Programs\\Python\\Python36', 'C:\\Users\\Users\\AppData\\Local\\Programs\\Python\\Python36\\DLLs', 'C:\\Users\\Users\\AppData\\Local\\Programs\\Python\\Python36\\Lib', 'C:\\Users\\hful\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\site-packages']`

**Comment by Ozeuth** [comment]
Dear hful,
And just to check, these are the library versions and paths used by the Houdini version?
(Eg. you have added the prints to the styler.py file, and are calling the Houdini plugin. So this should appear in the Houdini console.)

UPDATE: I got the exact same bug when using your version of tqdm (4.46.0). Can you please switch to 4.32.2 and see if it works now?

**Comment by hful** [comment]
Adding those prints to styler.py as you mentioned and run the Houdini version, didn't print version info in Houdini console.

**Comment by Ozeuth** [comment]
Hello hful,
Could you try the update, as suggested? Switch to tqdm (4.32.2) and rerun. I got the same error as you when running on 4.46.0

**Comment by hful** [comment]
switch to 4.32.2. still getting stuck and no version info printed

**Comment by hful** [comment]
Now every  setup I use is same with yours, except tf mine is 1.12.0. Hangs there still
CUDA: 10.1
CuDNN: 7.6.5
tensorflow: 1.12.0
tqdm: 4.32.2
matplotlib: 3.1.1
PIL: 6.1.0
imageio: 2.5.0
scipy: 1.2.0
skimage: 0.15.0

**Comment by hful** [comment]
During runtime some image files been written to the path "log/smoke_gun\0610_201220_fire". I believe the processing is partially successful.

**Comment by Ozeuth** [comment]
This is very unusual. I have similarly upgraded all my files to reflect yours (With the exception of tqdm) and I cannot replicate the bug. However, using tqdm = 4.46.0, I can get a similar bug to yours.

In such a scenario, I get folders d, r, and v, but only d and v filled with images (6 images in d, 3 images in v. Missing 1 image in r). This is because the prints from styler are not going to the subprocess pipe, which the Houdini code gets stuck waiting on. Give me a while to look into this

**Comment by Ozeuth** [comment]
Hello hful,
I've pushed a fix that solves the similar bug (That I receive when using tqdm = 4.46.0). I believe this will also solve your problem. Could you pull it and check?

**Comment by hful** [comment]
Tested. Working! Thank you:)

**Comment by Ozeuth** [comment]
Glad it works!
